# Generated by Django 2.0.6 on 2018-07-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
