# Generated by Django 2.0.6 on 2018-07-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuts', '0002_auto_20180725_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='SOME STRING', max_length=100, null=True),
        ),
    ]
